//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendancePC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSumView
    {
        public string Name { get; set; }
        public Nullable<int> Missing { get; set; }
        public Nullable<int> Reasonable { get; set; }
        public Nullable<int> UnReasonable { get; set; }
    }
}
