//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendancePC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int IdUser { get; set; }
        public bool IsPrime { get; set; }
    
        public virtual User User { get; set; }
    }
}
