//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendancePC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonAttend
    {
        public int IdLesson { get; set; }
        public int IdStudent { get; set; }
        public string AttendChar { get; set; }
        public Nullable<bool> IsReasonable { get; set; }
        public string Comment { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
