//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendancePC.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IdSubject { get; set; }
        public byte DayOfWeek { get; set; }
        public byte OrderNumber { get; set; }
        public bool IsEven { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
